services:

  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./access.log:/var/log/nginx/access.log'
    ports:
      - "8000:3000"
    depends_on:
      - "app1"
      - "app2"
      - "app3"
  app1:
    build:
      context: ./node-hello-app
      dockerfile: Dockerfile
    image: node-api
    container_name: node-api1
    volumes:
      - ./node-hello-app:/app
    environment:
      - APPID=1111
  app2:
    build:
      context: ./node-hello-app
      dockerfile: Dockerfile
    image: node-api
    container_name: node-api2
    environment:
      - APPID=2222
  app3:
    build:
      context: ./node-hello-app
      dockerfile: Dockerfile
    image: node:api
    container_name: node-api3
    environment:
      - APPID=3333
