services:
  api:
    build:
      context: ./node-hello-app
      dockerfile: Dockerfile.prod
    image: node-api:1.0.0
    ports:
      - "1000:3000"
    volumes:
      - ./node-hello-app:/app
    environment:
      - API_KEY=jgdjgsjgdsjgduttt
